# Generated by Django 4.2.1 on 2023-06-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductTitle', models.CharField(max_length=255)),
                ('ProductPrice', models.IntegerField()),
                ('ProductType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('UserEmail', models.EmailField(max_length=254)),
                ('UserAddress', models.CharField(max_length=255)),
                ('UserPhone', models.IntegerField()),
                ('UserPassword', models.CharField(max_length=255)),
                ('UserTypeId', models.IntegerField(default=0)),
            ],
        ),
    ]
